# Generated by Django 5.1.1 on 2024-11-25 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SIA102", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientDischargeArchive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("patient_type", models.CharField(max_length=50)),
                ("age", models.IntegerField()),
                ("sex", models.CharField(max_length=10)),
                ("date_of_birth", models.DateField()),
                ("admission_date", models.DateTimeField()),
                ("discharge_date", models.DateTimeField(blank=True, null=True)),
                ("attending_physician", models.CharField(max_length=255)),
                ("diagnosis", models.CharField(max_length=255)),
                ("approved_by", models.CharField(max_length=255)),
                ("discharged_by", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Medication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("medication_name", models.CharField(max_length=255)),
                ("medication_remarks", models.TextField()),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medications",
                        to="SIA102.patientdischargearchive",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IVTreatment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("bottle_no", models.CharField(max_length=50)),
                ("iv_solution", models.CharField(max_length=255)),
                ("volume", models.CharField(max_length=50)),
                ("incorporation", models.CharField(max_length=255)),
                ("regulation", models.CharField(max_length=255)),
                ("start_time", models.TimeField()),
                ("end_time", models.DateTimeField()),
                ("remarks", models.TextField()),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="iv_treatments",
                        to="SIA102.patientdischargearchive",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IVSideDrip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("bottle_no", models.CharField(max_length=50)),
                ("iv_solution", models.CharField(max_length=255)),
                ("volume", models.CharField(max_length=50)),
                ("incorporation", models.CharField(max_length=255)),
                ("regulation", models.CharField(max_length=255)),
                ("start_time", models.TimeField()),
                ("end_time", models.DateTimeField()),
                ("remarks", models.TextField()),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="iv_side_drips",
                        to="SIA102.patientdischargearchive",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IVFastDrip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("ivf", models.CharField(max_length=255)),
                ("volume", models.CharField(max_length=50)),
                ("incorporation", models.CharField(max_length=255)),
                ("time_taken", models.TimeField()),
                ("remarks", models.TextField()),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="iv_fast_drips",
                        to="SIA102.patientdischargearchive",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InitialVital",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                ("weight", models.CharField(max_length=20)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="initial_vitals",
                        to="SIA102.patientdischargearchive",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VitalSign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("temperature", models.FloatField()),
                ("pulse", models.IntegerField()),
                ("respiration", models.IntegerField()),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vital_signs",
                        to="SIA102.patientdischargearchive",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VitalSignOutput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("blood_pressure", models.CharField(max_length=15)),
                ("urine", models.IntegerField()),
                ("stool", models.IntegerField()),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vital_sign_outputs",
                        to="SIA102.patientdischargearchive",
                    ),
                ),
            ],
        ),
    ]
