# Generated by Django 5.1.1 on 2024-11-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SIA102", "0002_patientdischargearchive_medication_ivtreatment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientdischargearchive",
            name="address",
            field=models.TextField(default="Address not provided"),
        ),
        migrations.AddField(
            model_name="patientdischargearchive",
            name="room_number",
            field=models.CharField(default="Address not provided", max_length=50),
            preserve_default=False,
        ),
    ]
