# Generated by Django 5.1.1 on 2024-11-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SIA102", "0003_patientdischargearchive_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientdischargearchive",
            name="room_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
