# Generated by Django 5.1.1 on 2024-11-25 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SIA102", "0004_alter_patientdischargearchive_room_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientdischargearchive",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
