# Generated by Django 5.1.1 on 2024-11-25 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SIA102", "0005_alter_patientdischargearchive_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientdischargearchive",
            name="patientID",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="patientdischargearchive",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
